"""One-off: turn a photo into a 24x24 cross-stitch grid (ART rows + PALETTE)
for the embroidery-hoop toy. Outputs JS-ready text to paste into hoop.js.

Pipeline: load -> square center-crop -> downscale to GRID -> quantize to a
small embroidery-thread palette -> map each cell to a palette letter ->
optionally blank cells outside the hoop circle so the portrait reads as a disc.
"""
import sys
from PIL import Image
import numpy as np

SRC = "public/images/pizza.png"
GRID = 24
# Slight downscale supersample for cleaner averaging before final GRID.
SUPERSAMPLE = 4

# Embroidery thread palette — letter -> (name, RGB). Kept small so the result
# reads as cross-stitch, not a photo. Tuned for a hooded portrait (dark hood,
# warm skin, dark hair, teeth/pizza highlight, background).
PALETTE = {
    "K": ("hood/jacket dark", (38, 38, 44)),
    "H": ("hair near-black",  (20, 18, 22)),
    "S": ("skin",             (214, 158, 120)),
    "L": ("skin highlight",   (236, 196, 164)),
    "E": ("shadow/eyes",      (70, 52, 46)),
    "P": ("pizza/teeth warm", (228, 206, 150)),
    "B": ("background cool",  (96, 104, 112)),
}

def nearest(rgb, palette_rgbs):
    d = np.sum((palette_rgbs - rgb) ** 2, axis=1)
    return int(np.argmin(d))

def main():
    img = Image.open(SRC).convert("RGB")
    w, h = img.size
    # Crop box around the head as fractions of the source (face sits left-center
    # in the landscape photo). Tunable via argv: l t r b (fractions).
    if len(sys.argv) >= 5:
        fl, ft, fr, fb = (float(x) for x in sys.argv[1:5])
    else:
        fl, ft, fr, fb = 0.27, 0.02, 0.66, 0.98
    box = (int(fl * w), int(ft * h), int(fr * w), int(fb * h))
    img = img.crop(box)
    # Pad to a square so the face isn't distorted when squished to the grid.
    cw, ch = img.size
    side = max(cw, ch)
    sq = Image.new("RGB", (side, side), (96, 104, 112))  # bg-ish fill
    sq.paste(img, ((side - cw) // 2, (side - ch) // 2))
    img = sq

    img = img.resize((GRID * SUPERSAMPLE, GRID * SUPERSAMPLE), Image.LANCZOS)
    img = img.resize((GRID, GRID), Image.BILINEAR)
    arr = np.asarray(img, dtype=np.float32)

    letters = list(PALETTE.keys())
    rgbs = np.array([PALETTE[k][1] for k in letters], dtype=np.float32)

    cx = cy = (GRID - 1) / 2.0
    radius = GRID / 2.0  # disc mask radius in cells

    rows = []
    for r in range(GRID):
        line = []
        for c in range(GRID):
            # Blank cells outside the hoop disc.
            if (c - cx) ** 2 + (r - cy) ** 2 > radius ** 2:
                line.append(".")
                continue
            idx = nearest(arr[r, c], rgbs)
            line.append(letters[idx])
        rows.append("".join(line))

    # Emit JS.
    print("// --- generated by scripts/gen_hoop_portrait.py from", SRC, "---")
    print("const PALETTE = {")
    for k in letters:
        name, (R, G, B) = PALETTE[k]
        print(f"    {k}: '#{R:02X}{G:02X}{B:02X}',  // {name}")
    print("  };\n")
    print("const ART = [")
    for line in rows:
        print(f"    '{line}',")
    print("  ];")

    # Quick histogram so we can sanity-check the mix.
    from collections import Counter
    cnt = Counter("".join(rows).replace(".", ""))
    sys.stderr.write("cell counts: " + ", ".join(f"{k}={cnt[k]}" for k in letters) + "\n")

if __name__ == "__main__":
    main()
